const databank = [
  {
    id: 1,
    faculty: "Education",
    courseCode: "GST101",
    courseTitle: "Introduction to Study Guide",
    creditUnit: 2,
    level: "100",
    semester: "1",
    questions: [
      {
        question: "What is the capital of Nigeria?",
        optionA: "Lagos",
        optionB: "Abuja",
        optionC: "Uyo",
        optionD: "Enugu",
        answer: "optionB",
      },
      {
        question: "What is the capital of Akwa Ibom?",
        optionA: "Lagos",
        optionB: "Abuja",
        optionC: "Uyo",
        optionD: "Itu",
        answer: "optionC",
      },
      {
        question: "What is the capital of Cross River?",
        optionA: "Ikom",
        optionB: "Odukpani",
        optionC: "Efik",
        optionD: "Calabar",
        answer: "optionD",
      },
      {
        question: "What is the capital of Rivers?",
        optionA: "Ibadan",
        optionB: "Ikwere",
        optionC: "Port Harcourt",
        optionD: "Andoni",
        answer: "optionC",
      },
      {
        question: "What is the headquaters of Uruan?",
        optionA: "Idu",
        optionB: "Eman Ikot Ebo",
        optionC: "Ifianyong",
        optionD: "Mbiakong",
        answer: "optionA",
      },
    ],
  },
  {
    id: 2,
    faculty: "Science",
    courseCode: "CIT103",
    courseTitle: "Introduction to Computers",
    creditUnit: 2,
    level: "100",
    semester: "1",
    questions: [
      {
        question: "What is the capital of Nigeria?",
        optionA: "Lagos",
        optionB: "Abuja",
        optionC: "Uyo",
        optionD: "Enugu",
        answer: "optionB",
      },
      {
        question: "What is the capital of Akwa Ibom?",
        optionA: "Lagos",
        optionB: "Abuja",
        optionC: "Uyo",
        optionD: "Itu",
        answer: "optionC",
      },
      {
        question: "What is the capital of Cross River?",
        optionA: "Ikom",
        optionB: "Odukpani",
        optionC: "Efik",
        optionD: "Calabar",
        answer: "optionD",
      },
      {
        question: "What is the capital of Rivers?",
        optionA: "Ibadan",
        optionB: "Ikwere",
        optionC: "Port Harcourt",
        optionD: "Andoni",
        answer: "optionC",
      },
      {
        question: "What is the headquaters of Uruan?",
        optionA: "Idu",
        optionB: "Eman Ikot Ebo",
        optionC: "Ifianyong",
        optionD: "Mbiakong",
        answer: "optionA",
      },
    ],
  },
  {
    id: 3,
    faculty: "Arts",
    courseCode: "ENG101",
    courseTitle: "Introduction to English Studies",
    creditUnit: 2,
    level: "100",
    semester: "1",
    questions: [
      {
        question: "What is the capital of Nigeria?",
        optionA: "Lagos",
        optionB: "Abuja",
        optionC: "Uyo",
        optionD: "Enugu",
        answer: "optionB",
      },
      {
        question: "What is the capital of Akwa Ibom?",
        optionA: "Lagos",
        optionB: "Abuja",
        optionC: "Uyo",
        optionD: "Itu",
        answer: "optionC",
      },
      {
        question: "What is the capital of Cross River?",
        optionA: "Ikom",
        optionB: "Odukpani",
        optionC: "Efik",
        optionD: "Calabar",
        answer: "optionD",
      },
      {
        question: "What is the capital of Rivers?",
        optionA: "Ibadan",
        optionB: "Ikwere",
        optionC: "Port Harcourt",
        optionD: "Andoni",
        answer: "optionC",
      },
      {
        question: "What is the headquaters of Uruan?",
        optionA: "Idu",
        optionB: "Eman Ikot Ebo",
        optionC: "Ifianyong",
        optionD: "Mbiakong",
        answer: "optionA",
      },
    ],
  },
  {
    id: 4,
    faculty: "Management Science",
    courseCode: "PUL101",
    courseTitle: "Introduction to Public Institutions",
    creditUnit: 2,
    level: "100",
    semester: "1",
    questions: [
      {
        question: "What is the capital of Nigeria?",
        optionA: "Lagos",
        optionB: "Abuja",
        optionC: "Uyo",
        optionD: "Enugu",
        answer: "optionB",
      },
      {
        question: "What is the capital of Akwa Ibom?",
        optionA: "Lagos",
        optionB: "Abuja",
        optionC: "Uyo",
        optionD: "Itu",
        answer: "optionC",
      },
      {
        question: "What is the capital of Cross River?",
        optionA: "Ikom",
        optionB: "Odukpani",
        optionC: "Efik",
        optionD: "Calabar",
        answer: "optionD",
      },
      {
        question: "What is the capital of Rivers?",
        optionA: "Ibadan",
        optionB: "Ikwere",
        optionC: "Port Harcourt",
        optionD: "Andoni",
        answer: "optionC",
      },
      {
        question: "What is the headquaters of Uruan?",
        optionA: "Idu",
        optionB: "Eman Ikot Ebo",
        optionC: "Ifianyong",
        optionD: "Mbiakong",
        answer: "optionA",
      },
    ],
  },
  {
    id: 5,
    faculty: "Management Science",
    courseCode: "PUL102",
    courseTitle: "Introduction to Public Institutions II",
    creditUnit: 2,
    level: "100",
    semester: "2",
    questions: [
      {
        question: "What is the capital of Nigeria?",
        optionA: "Lagos",
        optionB: "Abuja",
        optionC: "Uyo",
        optionD: "Enugu",
        answer: "optionB",
      },
      {
        question: "What is the capital of Akwa Ibom?",
        optionA: "Lagos",
        optionB: "Abuja",
        optionC: "Uyo",
        optionD: "Itu",
        answer: "optionC",
      },
      {
        question: "What is the capital of Cross River?",
        optionA: "Ikom",
        optionB: "Odukpani",
        optionC: "Efik",
        optionD: "Calabar",
        answer: "optionD",
      },
      {
        question: "What is the capital of Rivers?",
        optionA: "Ibadan",
        optionB: "Ikwere",
        optionC: "Port Harcourt",
        optionD: "Andoni",
        answer: "optionC",
      },
      {
        question: "What is the headquaters of Uruan?",
        optionA: "Idu",
        optionB: "Eman Ikot Ebo",
        optionC: "Ifianyong",
        optionD: "Mbiakong",
        answer: "optionA",
      },
    ],
  },
  {
    id: 6,
    faculty: "Science",
    courseCode: "BIO101",
    courseTitle: "Introduction to Biology",
    creditUnit: 2,
    level: "100",
    semester: "1",
    questions: [
      {
        question: "What is the capital of Nigeria?",
        optionA: "Lagos",
        optionB: "Abuja",
        optionC: "Uyo",
        optionD: "Enugu",
        answer: "optionB",
      },
      {
        question: "What is the capital of Akwa Ibom?",
        optionA: "Lagos",
        optionB: "Abuja",
        optionC: "Uyo",
        optionD: "Itu",
        answer: "optionC",
      },
      {
        question: "What is the capital of Cross River?",
        optionA: "Ikom",
        optionB: "Odukpani",
        optionC: "Efik",
        optionD: "Calabar",
        answer: "optionD",
      },
      {
        question: "What is the capital of Rivers?",
        optionA: "Ibadan",
        optionB: "Ikwere",
        optionC: "Port Harcourt",
        optionD: "Andoni",
        answer: "optionC",
      },
      {
        question: "What is the headquaters of Uruan?",
        optionA: "Idu",
        optionB: "Eman Ikot Ebo",
        optionC: "Ifianyong",
        optionD: "Mbiakong",
        answer: "optionA",
      },
    ],
  },
  {
    id: 7,
    faculty: "Science",
    courseCode: "PHY101",
    courseTitle: "Introduction to Physics",
    creditUnit: 2,
    level: "100",
    semester: "1",
    questions: [
      {
        question: "What is the capital of Nigeria?",
        optionA: "Lagos",
        optionB: "Abuja",
        optionC: "Uyo",
        optionD: "Enugu",
        answer: "optionB",
      },
      {
        question: "What is the capital of Akwa Ibom?",
        optionA: "Lagos",
        optionB: "Abuja",
        optionC: "Uyo",
        optionD: "Itu",
        answer: "optionC",
      },
      {
        question: "What is the capital of Cross River?",
        optionA: "Ikom",
        optionB: "Odukpani",
        optionC: "Efik",
        optionD: "Calabar",
        answer: "optionD",
      },
      {
        question: "What is the capital of Rivers?",
        optionA: "Ibadan",
        optionB: "Ikwere",
        optionC: "Port Harcourt",
        optionD: "Andoni",
        answer: "optionC",
      },
      {
        question: "What is the headquaters of Uruan?",
        optionA: "Idu",
        optionB: "Eman Ikot Ebo",
        optionC: "Ifianyong",
        optionD: "Mbiakong",
        answer: "optionA",
      },
    ],
  },
  {
    id: 8,
    faculty: "Education",
    courseCode: "EDU114",
    courseTitle: "Education in Nigeria",
    creditUnit: 2,
    level: "100",
    semester: "1",
    questions: [
      {
        question: "What is the capital of Nigeria?",
        optionA: "Lagos",
        optionB: "Abuja",
        optionC: "Uyo",
        optionD: "Enugu",
        answer: "optionB",
      },
      {
        question: "What is the capital of Akwa Ibom?",
        optionA: "Lagos",
        optionB: "Abuja",
        optionC: "Uyo",
        optionD: "Itu",
        answer: "optionC",
      },
      {
        question: "What is the capital of Cross River?",
        optionA: "Ikom",
        optionB: "Odukpani",
        optionC: "Efik",
        optionD: "Calabar",
        answer: "optionD",
      },
      {
        question: "What is the capital of Rivers?",
        optionA: "Ibadan",
        optionB: "Ikwere",
        optionC: "Port Harcourt",
        optionD: "Andoni",
        answer: "optionC",
      },
      {
        question: "What is the headquaters of Uruan?",
        optionA: "Idu",
        optionB: "Eman Ikot Ebo",
        optionC: "Ifianyong",
        optionD: "Mbiakong",
        answer: "optionA",
      },
    ],
  },
  {
    id: 9,
    faculty: "Education",
    courseCode: "EDU426",
    courseTitle: "Special Education",
    creditUnit: 2,
    level: "400",
    semester: "2",
    questions: [
      {
        question: "What is the capital of Nigeria?",
        optionA: "Lagos",
        optionB: "Abuja",
        optionC: "Uyo",
        optionD: "Enugu",
        answer: "optionB",
      },
      {
        question: "What is the capital of Akwa Ibom?",
        optionA: "Lagos",
        optionB: "Abuja",
        optionC: "Uyo",
        optionD: "Itu",
        answer: "optionC",
      },
      {
        question: "What is the capital of Cross River?",
        optionA: "Ikom",
        optionB: "Odukpani",
        optionC: "Efik",
        optionD: "Calabar",
        answer: "optionD",
      },
      {
        question: "What is the capital of Rivers?",
        optionA: "Ibadan",
        optionB: "Ikwere",
        optionC: "Port Harcourt",
        optionD: "Andoni",
        answer: "optionC",
      },
      {
        question: "What is the headquaters of Uruan?",
        optionA: "Idu",
        optionB: "Eman Ikot Ebo",
        optionC: "Ifianyong",
        optionD: "Mbiakong",
        answer: "optionA",
      },
    ],
  },
];

export default databank;
